### ISSUE TITLE
Enhancement suggestions for pg-collector

### ISSUE THREAD

**Issue by thottr** [awslabs/pg-collector#1]
1) Consider Adding queryid to the tables in sql_stat_statements sections
2) Consider Adding a table that gives sql statements ordered by shared_blks_read that can help identify the top sql statements issuing physical reads
3) Consider Adding a section of information from pg_statio_all_tables, that shows the top tables that are getting the physical reads (heap_blks_read+idx_blks_read+toast_blks_read+tidx_blks_read)

**Comment by mmohali** [comment]
i added below to v2.9 , thanks for your suggestions .

1.  Add queryid to the pg_stat_statements's queries ( pg_stat_statements extension section)
2. Add Top SQL order by shared blocks read (physical reads)  ( pg_stat_statements extension section)
3. Add Top 50 Tables by total physical reads and total physical reads percent to Table Access Profile section
4. Add Top 50 indexes by physical reads and physical reads percent to Index Access Profile section
