### ISSUE TITLE
pg_collector update queries against pg_stat_statements for postgres 13

### ISSUE THREAD

**Issue by thottr** [awslabs/pg-collector#2]
The columns in the view pg_stat_statements (created by the postgres extension pg_stat_statements) has changed in [postgres 13](https://www.postgresql.org/docs/13/pgstatstatements.html). Queries against pg_stat_statements, in pg_collector should be updated to reflect the new column names.

**Comment by mmohali** [comment]
i fixed it i pg-collector V1 for PostgreSQL 13  https://github.com/awslabs/pg-collector/releases/tag/pg-collector-V1-for-PostgreSQL-13

Starting from PostgreSQL 13, PG Collector will have a dedicated script for each PostgreSQL major version .

each PG Collector major version will have it is own branch and the main branch will be for PG Collector that support PostgreSQL 12 and older versions
i updated the main https://github.com/awslabs/pg-collector read me for the new Versioning Policy , please take a look .
to access   pg-collector releases  https://github.com/awslabs/pg-collector/releases
