### ISSUE TITLE
pg14

### ISSUE THREAD

**Issue by veragini** [awslabs/pg-collector#4]
Hi Team,

I was wondering if I'm making a mistake or if there is in fact a bug ? I'm testing it in Postgres 14. Thanks. Part of the error:

sql:./pg_collector.sql:217: ERROR:  syntax error at or near "<!"
LINE 1: <!DOCTYPE html>
        ^
psql:./pg_collector.sql:256: ERROR:  syntax error at or near "up"
LINE 1: up
        ^
psql:./pg_collector.sql:1252: error: invalid command \H</td>
psql:./pg_collector.sql:1256: error: invalid command \<span
Report name <span class="pl-k">and</span> location: <span class="pl-k">/</span>tmp<span class="pl-k">/</span>pg_collector_:<span class="pl-c1">filename</span>.<span class="pl-c1">html</span></td>
psql:./pg_collector.sql:1264: warning: \o: extra argument "class="pl-k">/</span>tmp<span" ignored
psql:./pg_collector.sql:1264: warning: \o: extra argument "class="pl-k">/</span>pg_collector_:<span" ignored
psql:./pg_collector.sql:1264: warning: \o: extra argument "class="pl-c1">filename</span>.<span" ignored
psql:./pg_collector.sql:1264: warning: \o: extra argument "class="pl-c1">html</span></td>" ignored
psql:./pg_collector.sql:1268: error: unrecognized value "off</td>" for "footer": Boolean expected
psql:./pg_collector.sql:1488: error: invalid command \<span

psql:./pg_collector.sql:1492: ERROR:  syntax error at or near "</"
LINE 1: </span> as avers<span class="pl-pds">&#39;

`
UPDATE here. I figured the above out. there were some funny characters from the wget (download). I fixed it, the above errors gone. However the following still around. perhaps due to PG version ?`

metabase=# \i pg_collector.sql
Output format is html.
Report name and location: /tmp/pg_collector_metabase-2021-10-08_111143.html
psql:pg_collector.sql:816: ERROR:  column "total_time" does not exist
LINE 2: round(total_time::numeric, 2) as total_time_Msec, 
              ^
psql:pg_collector.sql:834: ERROR:  column "total_time" does not exist
LINE 2: round(total_time::numeric, 2) as total_time_Msec, 
              ^
psql:pg_collector.sql:852: ERROR:  column "total_time" does not exist
LINE 2: round(total_time::numeric, 2) as total_time_Msec, 
              ^
psql:pg_collector.sql:870: ERROR:  column "total_time" does not exist
LINE 2: round(total_time::numeric, 2) as total_time_Msec, 
              ^
psql:pg_collector.sql:889: ERROR:  column "total_time" does not exist
LINE 2: round(total_time::numeric, 2) as total_time_Msec, 
              ^
psql:pg_collector.sql:906: error: Did not find any settings.
psql:pg_collector.sql:2181: WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted

**Comment by veragini** [comment]
It appears from version 13 and 14 the column total_time is replaced to total_exec_time

Also for these:

stddev_exec_time
mean_exec_time

Doco for <=12
https://www.postgresql.org/docs/12/pgstatstatements.html

```
Name        | Type         | References | Description
total_time | double precision |   | Total time spent in the statement, in milliseconds
```

13 and 14
https://www.postgresql.org/docs/13/pgstatstatements.html

```
total_exec_time double precision

Total time spent executing the statement, in milliseconds
```

Below query updated:

```
select queryid,substring(query,1,60) as query , calls,
round(total_exec_time::numeric, 2) as total_time_Msec,
round((total_exec_time::numeric/1000), 2) as total_time_sec,
round(mean_exec_time::numeric,2) as avg_time_Msec,
round((mean_exec_time::numeric/1000),2) as avg_time_sec,
round(stddev_exec_time::numeric, 2) as standard_deviation_time_Msec,
round((stddev_exec_time::numeric/1000), 2) as standard_deviation_time_sec,
round(rows::numeric/calls,2) rows_per_exec,
round((100 * total_exec_time / sum(total_exec_time) over ())::numeric, 4) as percent
from pg_stat_statements
order by total_time_Msec desc limit 20;
```

**Comment by veragini** [comment]
I made some changes. Any idea?

```
cp pg_collector.sql pg_collector_13_14.sql
sed -i 's/total_time/total_exec_time/g' pg_collector_13_14.sql
sed -i 's/stddev_time/stddev_exec_time/g' pg_collector_13_14.sql
sed -i 's/mean_time/mean_exec_time/g' pg_collector_13_14.sql

```
OR

```
cp pg_collector.sql pg_collector_13_14.sql
gsed -i 's/total_time/total_exec_time/gI' pg_collector_13_14.sql
gsed -i 's/stddev_time/stddev_exec_time/gI' pg_collector_13_14.sql
gsed -i 's/mean_time/mean_exec_time/gI' pg_collector_13_14.sql

```

Make sure you fix the following one so that you prevent the below error:

```
postgres=# \i pg_collector_13_14.sql 
Output format is html.
Report name and location: /tmp/pg_collector_postgres-2021-10-08_120642.html
psql:pg_collector_13_14.sql:906: error: Did not find any settings.
psql:pg_collector_13_14.sql:2181: ERROR:  column "total_exec_time" does not exist
LINE 2: schemaname||'.'||funcname func_name, calls, total_exec_time,
                                                    ^
```

vi pg_collector_13_14.sql

```
2162 -- +----------------------------------------------------------------------------+
2163 -- |      - functions_statistics                             -                  |
2164 -- +----------------------------------------------------------------------------+
2165 
2166 
2167 \qecho <a name="functions_statistics"></a>
2168 \qecho <font size="+2" face="Arial,Helvetica,Geneva,sans-serif" color="#16191f"><b>Functions statistics</b></font><hr align="left" width="460">
2169 \qecho <br>
2170 \qecho <h4>The pg_stat_user_functions view will contain one row for each tracked function, showing statistics about executions of that function. </h4>
2171 \qecho <h4> The track_functions parameter controls exactly which functions are tracked. </h4>
2172 \qecho <h4>track_functions parameter Enables tracking of function call counts and time used. </h4>
2173 \qecho <h4>Specify pl to track only procedural-language functions, all to also track SQL and C language functions. </h4>
2174 \qecho <details>
2175 SELECT name,setting from pg_settings where name ='track_functions';
2176 \qecho <br>
2177 select
2178 schemaname||'.'||funcname func_name, calls, total_time,
2179 round((total_time/calls)::numeric,2) as mean_time, self_time
2180 from pg_catalog.pg_stat_user_functions
2181 order by total_time desc;
```

**Almost there:**

```
postgres=# \i pg_collector_13_14.sql                                                                                                                                                                             Output format is html.
Report name and location: /tmp/pg_collector_postgres-2021-10-08_121442.html
psql:pg_collector_13_14.sql:906: error: Did not find any settings.
postgres=# 
```

**Comment by mmohali** [comment]
i fixed it i pg-collector V1 for PostgreSQL 13  https://github.com/awslabs/pg-collector/releases/tag/pg-collector-V1-for-PostgreSQL-13

Starting from PostgreSQL 13, PG Collector will have a dedicated script for each PostgreSQL major version .

each PG Collector major version will have it is own branch and the main branch will be for PG Collector that support PostgreSQL 12 and older versions
i updated the main https://github.com/awslabs/pg-collector read me for the new Versioning Policy , please take a look .
to access   pg-collector releases  https://github.com/awslabs/pg-collector/releases

**Comment by mmohali** [comment]
pg collector V1.1 for PostgreSQL 14  https://github.com/awslabs/pg-collector/releases/tag/pg-collector-V1.1-for-PostgreSQL-14
