### ISSUE TITLE
Can we run pg_collector that supports for version 14 in postgres 15 or 16 DB

### ISSUE THREAD

**Issue by bala-gif** [awslabs/pg-collector#5]

**Comment by mmohali** [comment]
Technically yes but you may see some errors as sometimes newer version remove or rename some columns , you can edit the script and fix the issue and rerun the script .

also FYI , I am working on adding pg_collector  for 15 and 16 and it should be released within a week . for future releases  like postgres 17  i will do my best to release it in the same week .

**Comment by mmohali** [comment]
https://github.com/awslabs/pg-collector/tree/pg-collector-for-postgresql-16
https://github.com/awslabs/pg-collector/tree/pg-collector-for-postgresql-15
