### ISSUE TITLE
When pg_Collector dedicated sql  will be available for Postgres 15 and higher version

### ISSUE THREAD

**Issue by bramakrishnan-zuora** [awslabs/pg-collector#6]

**Comment by mmohali** [comment]
I am working on it and it should be released within a week .

**Comment by mmohali** [comment]
https://github.com/awslabs/pg-collector/tree/pg-collector-for-postgresql-16
https://github.com/awslabs/pg-collector/tree/pg-collector-for-postgresql-15

**Comment by onno-vos-dev** [comment]
@mmohali Can you please cut new releases for 15 and 16 so they're available in the https://github.com/awslabs/pg-collector/releases page? 👍

**Comment by mmohali** [comment]
@onno-vos-dev i will add it

**Comment by mmohali** [comment]
@onno-vos-dev Done , I created the releases for the latest versions 

pg collector V1 for PostgreSQL 16
pg collector V1 for PostgreSQL 15
pg collector V1.2 for PostgreSQL 14
pg collector V1.2 for PostgreSQL 13
PG Collector v3 for PostgreSQL 12 and older versions
